travis:
  secure:
    BINSTAR_TOKEN: LllKPS6oTrOSpDuCNOpGwpkzACQ+AsaOXVHjSp/kn56mKJgtZqklzxZrs3oasbe9FJXzRtPmBGBSAndcoGN28vADbg7lcv02HjuL8+tBBD1wjcCW18xTUxFv7cvoYDX8ocdAhKdh/TB0FrQCq63cAfKrMGPE6w7CgI5mK0gDsHy6IedbZsMHmWfbD5D+jIRhWG5ZLvVO1ZJzuLWZRnNDG91V2zBF3rk3k/PIpfFJSoQ20tQKIdpovkz8dLfcj1/MwuJ3aAe5z3sMrC9g0/3/T9YEWeLDRva5Yd76jnpsZrL8P/mrCvbcjczNURuOm+EEsaLWpMdOhlpAL0WLhwCV739Ft7XGwZiUCFKUZeT5VIOkuD9kWc1nFhYNSPQkypbFM5x0pma2kAVuvUvN44/gNhnV28XR4DIA+SwBnCI9RCgTB686GOlfBLbDrYt3e23DVB6b6rD71mwr+TOeIBZ6sj5ncCFWqkHwaHZ/VVZD7pIpOG1b+tLd5rfeSYxyEAeowl3BnifmZWRT4iN16K1jGU76NT9if6RNfS8vDiy1fIAB59bj0vhDTv+DLPxTH1iLnnn7fF1Q+8wuZ4gEdU9M3seYF6GVktl2djZVeCzaF9/U4urGSCzjC7Zyhwi12AZuf97vZW3zTjvlkcR1B2bhGW1O5413leR+/go+DtSt41I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
